justwrite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from users import views as user_views
from writing_env import views as writingEnv_views
from main import views as main_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('send-email/<str:username>/', user_views.send_verification_email, name='send-email'),
    path('email-sent/<str:username>/', user_views.email_sent, name='email-sent'),
    path('activate/<uidb64>/<token>/', user_views.activate, name='activate'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('', main_views.landing, name='landing'),
    path('home/', main_views.home, name='home'),
    path('user/', include('users.urls')),
    path('forest/', include('forest.urls')),
    path('project/', include('projects.urls')),
    path('writingEnv/', writingEnv_views.writingEnv, name='writingEnv'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from .views import ProjectUpdateView, ProjectDetailView, ProjectDeleteView

from . import views

urlpatterns = [
    path('<str:username>/', views.projects, name='projects'),
    path('<str:username>/new/', views.create_project, name='project-create'),
    path('<str:username>/<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('<str:username>/<int:pk>/edit/', ProjectUpdateView.as_view(), name='project-edit'),
    path('<str:username>/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
    #DEMO
    path('DEMO-SCRIPT', views.projects, name='DEMO-SCRIPT')
]

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<str:username>/', views.profile, name='profile'),
]

projects/models.py
import os

import tinymce
from django.db import models
from django.dispatch import receiver
from django.shortcuts import reverse
from django.forms.fields import *

from users.models import User
from .validators import validate_file_extension
import decimal
import string

import re, cgi
tag_re = re.compile(r'(<!--.*?-->|<[^>]*>)')

def user_directory_path(instance, filename):
    path = f'files/{instance.user}/'
    ext = os.path.splitext(filename)[1]
    format = instance.name + ext
    return os.path.join(path, format)


class Project(models.Model):

    COUNT_OPTIONS = [
        ('Words', (
                ('50W','50 Words'),
                ('100W', '100 Words'),
                ('200W', '200 Words'),
                ('500W', '500 Words'),
                ('1000W', '1000 Words'),
            )
        ),
        ('Time', (
              ('10M', '10 Minutes'),
              ('20M', '20 Minutes'),
              ('30M', '30 Minutes'),
              ('60M', '1 hour'),
              ('120M', '2 hours'),
          )
        ),
    ]

    PROGRESS_TYPES = (
        ('Automatic', 'Automatic'),
        ('manual', 'Manual')
    )

    worddict = {

        "50W":50,
        "100W": 100,
        "200W": 200,
        "500W": 500,
        "1000W": 1000
    }

    timedict = {

        "10M": 10,
        "20M": 20,
        "30M": 30,
        "60M": 60,
        "120M": 120
    }

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    file = models.FileField(upload_to=user_directory_path, validators=[validate_file_extension])
    goal = models.CharField(max_length=10, choices=COUNT_OPTIONS, default='50W', null=True)
    goalProgress = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True)
    progressTracker = models.CharField(max_length=9, choices=PROGRESS_TYPES, default='Automatic')

    fileContentsBefore = "test! file data not retrieved or displayed"
    fileContentsCurrent = ""
    fileContentsAfter = ""

    def __str__(self):
        return self.name

    def __init__(self, *args,**kwargs):
        super().__init__(*args, **kwargs)
        try:
            with open(str(self.file.path)) as f:
                self.fileContentsBefore = "".join(f.readlines())

        except:
            print("project constructor error")

    def get_absolute_url(self):
        return reverse('projects', kwargs={'username': self.user})

    def set_file_contents(self, sessionInProgress):
        with open(str(self.file.path)) as f:
            self.fileContentsBefore = f.readlines()
        #if sessionInProgress == False:
        #    with open(str(self.file.path)) as f:
        #        self.fileContentsBefore = f.readlines()
        #elif sessionInProgress == True:
        #    self.fileContents = f.readlines()
        #fileContents = ""

    def submit_file_contents(self, data):
        print("submit called")
        f = open(self.file.path, "w")
        f.write(data)
        f.close()

    def save_file_contents(self, data):
        print("save called")
        self.fileContentsCurrent = data
        #print(self.fileContentsCurrent)

    #data getters
    #sanatises model fields into form fields to support localisation e.g. maths

    def get_goal_progress(self):

        #return #float('{}'.format(self.goalProgress))
        return self.goalProgress

    def get_streak(self):
        return int(self.goalProgress)

    def get_word_count(self, data):
        no_tags = tag_re.sub('',data)
        no_nbsp = no_tags.replace("&nbsp"," ")
        word_count = sum(word.strip(string.punctuation).isalpha() for word in no_nbsp.split())
        return word_count


    #progress setter
    def set_streak(self, data):
        if "W" in self.goal:
            self.goalProgress = self.get_word_count(data)/self.worddict[self.goal]

        elif "M" in self.goal:
            self.goalProgress = data / self.timedict[self.goal]

        else:
            print("error in goal_type set_streak function")





@receiver(models.signals.post_delete, sender=Project)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem when
    corresponding 'Project' is deleted
    """
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)


@receiver(models.signals.pre_save, sender=Project)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `Project` is updated
    with new file.
    """
    if not instance.pk:
        return False

    try:
        old_file = Project.objects.get(pk=instance.pk).file
    except Project.DoesNotExist:
        return False

    new_file = instance.file
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

projects/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from justwrite.settings import file_intro
from .models import Project


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ('name', 'file')



    def file_check(self, file, name):
        if file is None:
            print("a")
            f = open(name, "w")
            f.write(file_intro)
            f.close()
            return f
        elif file is not None:
            print("B")
            return file

        else:
            print("Error: file_check projects/forms.py")

    def form_valid(self, form):
        project = form.save(commit=False)
        project.user = self.request.user

        if project.file is None:
            f = open(form.name, "w")
            f.write(file_intro)
            project.file = f
            print("Null!")
        elif project.file is not None:
            project.file = project.file
            print("not null?")

        else:
            print("Error: file_check projects/forms.py")

        form.save()

projects/views.py
import tinymce
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.contrib import messages

from .forms import ProjectForm
from users.models import User
from .models import Project
from typing import Type


@login_required
def projects(request, username):
    """
    Displays projects of requested user if
    user is authenticated.
    """
    user = get_object_or_404(User, username=username)
    context = {
        'user': user,
    }
    if request.user.is_authenticated and request.user == user:  # logged-in user == requested user
        return render(request, 'projects/myprojects.html', context)
    else:  # return view-only profile page
        return render(request, 'projects/projects.html', context)


def create_project(request, username):
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        user = User.objects.get(username=username)
        form.instance.user = user
        #form.file = form.file_check(form)
        file = request.POST.get('file')
        name = request.POST.get('name')
        #file.value = form.file_check(file, name)
        #file.save()
        if form.is_valid():
            form.save()
            print("project create success")
            return redirect('projects', request.user)
        else:
            print("project create failed")
    else:
        form = ProjectForm()
    return render(request, 'projects/project_form.html', {'form': form})


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    sessionInProgress = False


    def get_context_data(self, **kwargs):
        pk = self.kwargs['pk']
        project = Project.objects.get(id=pk)
        project.set_file_contents(self.sessionInProgress)
        #print(project.name)
        #print(project.fileContentsBefore)
        #tinymce.activeEditor.setContent(project.fileContents)
        return super(ProjectDetailView, self).get_context_data()

    def post(self, request, **kwargs):
        self.sessionInProgress = True
        pk = self.kwargs['pk']
        project = Project.objects.get(id=pk)
        if project.progressTracker == 'Automatic':
            project.set_streak(request.POST.get('writingEnv'))
            project.save()
        project.save_file_contents(request.POST.get('writingEnv'))
        project.submit_file_contents(request.POST.get('writingEnv'))
        return HttpResponseRedirect(self.request.path_info)




class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    fields = ['name', 'file', 'goal', 'progressTracker']

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, 'Project successfully created.')
        return super().form_valid(form)


class ProjectUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Project
    fields = ['name', 'file', 'goal', 'progressTracker', 'goalProgress']

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        context['goalProgress'] = self.get_object().get_goal_progress()
        #print(self.get_object().get_goal_progress())
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, 'Project successfully created.')
        return super().form_valid(form)

    def test_func(self):
        project = self.get_object()
        if self.request.user == project.user:
            return True
        return False


class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Project

    def get_success_url(self):
        return reverse('projects', kwargs={'username': self.request.user})

    def test_func(self):
        project = self.get_object()
        if self.request.user == project.user:
            return True
        return False

templates/projects/myprojects.html
{% extends "main/base.html" %}
{% block content %}
    <div class="projects-main-box">
        <div class="projects-top-row">
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'project-create' user %}">Create new</a>
            <h3>Projects</h3>
            <div class="streak-box">
                <h3>{{ user.profile.streak }}</h3>
            </div>
        </div>
        
        {% for project in user.project_set.all %}
            <div class="project-box">
                <h4>{{ project.name }}</h4>
                <div class="btn-container">
                    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'project-delete' project.user project.id %}">Delete</a>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'project-edit' project.user project.id %}">Edit</a>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'project-detail' project.user project.id %}">Write</a>
                </div>
            </div>
            <br>
        {% endfor %}
    </div>
{% endblock content %}

templates/projects/project_confirm_delete.html
{% extends "main/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" c>
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Project</legend>
                <h2>Are you sure you want to delete the project: {{ object.name }}?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, delete</button>
                <button class="btn btn-outline-secondary" type="submit">No, take me back</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/projects/project_detail.html
{% extends "main/base.html" %}
{% block content %}
<div class="projects-main-box">
  <div class="projects-top-row">
    <a class="mr-2" href="{% url 'profile' object.user %}">{{ object.user }}</a>
    <h3>{{ object.name }}</h3>
    <div class="streak-box">
      <h3>{{ user.profile.streak }}</h3>
    </div>
  </div>

  <div class="writing-box">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <textarea name="writingEnv" id="writingEnv" style="height: 100vh" >{{ project.fileContentsBefore}}</textarea>
        <div class="form-group">
            <button class="btn btn-outline-info" type="Submitbtn" >Submit Changes</button>
        </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/projects/project_form.html
{% extends "main/landing_base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'formset/jquery.formset.js' %}"></script>
<script>
    function Hide() {
        if(document.getElementById('id_progressTracker').options[document.getElementById('id_progressTracker').selectedIndex].value == "Automatic") {
             document.getElementById('div_id_goalProgress').style.display = 'none';
        }
        else {
             document.getElementById('div_id_goalProgress').style.display = '';
        }
    };  </script>
<script type="text/javascript"> window.addEventListener("load", Hide);</script> <script type="text/javascript"> var el = document.getElementById("div_id_progressTracker"); el.addEventListener("click", Hide);</script>
    <div>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">

                        <strong>{{ field.name }}: {{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="form-box">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Project</legend>
                <p> {{ goalProgress }} Times Completed </p>
                <div class="col-sm-12">
                    {{ form|crispy }}
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Confirm</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/projects/projects.html
{% extends "main/base.html" %}
{% block content %}
    <h1>{{ user }}'s projects</h1>
{% endblock content %}