forest/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<str:username>/', views.forest, name='forest'),
    path('<str:username>/add-tree', views.add_tree, name='add-tree'),
]

justwrite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from users import views as user_views
from writing_env import views as writingEnv_views
from main import views as main_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('send-email/<str:username>/', user_views.send_verification_email, name='send-email'),
    path('email-sent/<str:username>/', user_views.email_sent, name='email-sent'),
    path('activate/<uidb64>/<token>/', user_views.activate, name='activate'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('', main_views.landing, name='landing'),
    path('home/', main_views.home, name='home'),
    path('user/', include('users.urls')),
    path('forest/', include('forest.urls')),
    path('project/', include('projects.urls')),
    path('writingEnv/', writingEnv_views.writingEnv, name='writingEnv'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<str:username>/', views.profile, name='profile'),
]

forest/models.py
from django.db import models

from users.models import User


class Forest(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f"{self.user}'s forest"

    def add_tree(self):
        Tree.objects.create(forest=self)


class Tree(models.Model):
    forest = models.ForeignKey(
        Forest,
        on_delete=models.CASCADE,
    )

forest/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from users.models import User


@login_required
def forest(request, username):
    user = get_object_or_404(User, username=username)
    context = {'user': user}
    if request.user == user:
        return render(request, 'forest/myforest.html', context)
    else:
        return render(request, 'forest/forest.html', context)


@login_required
def add_tree(request, username):
    user = get_object_or_404(User, username=username)
    if request.user == user:
        user.forest.add_tree()
    return redirect('forest', user)

templates/forest/forest.html
{% extends "main/base.html" %}
{% block content %}
    <div class="content-section">
        <h3>{{ user }}'s Forest</h3>
        {% for tree in user.forest.tree_set.all %}
            <div class="content-section">
                <a class="mr-2" href="#">Tree</a>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

templates/forest/myforest.html
{% extends "main/base.html" %}
{% load static %}
{% block content %}
    <div class="forest-main-box">
        <div class="forest-top-row">
            <br>
            <div class="title">
                <h3>{{ user }}'s Forest</h3>
            </div>
            <div class="streak-box">
                <h3>{{ user.profile.streak }}</h3>
            </div>
        </div>
        <div class="forest-image">
            <h3>trees here</h3>
            <div class="forest-top-row">
                {% for tree in user.forest.tree_set.all %}
                <div class="tree-image">
                    <img src="{% static 'images/tree.png' %}">
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="forest-top-row">
            <div class="btn-container">
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'add-tree' user %}">Add tree</a>
            </div>
        </div>
    </div>
{% endblock content %}